### ISSUE TITLE
Few files for upload and save in the database

### ISSUE THREAD

**Issue by typo3ua** [sebkln/form_examples#1]
**I need to add few files for upload and save in the database.**
I have this code in the YAML:
```
[...]
      -
        table: tx_answers_domain_model_answer
        mode: insert
        databaseColumnMappings:
          pid:
            value: '0'
          datetime:
            value: '{__currentTimestamp}'
          tstamp:
            value: '{__currentTimestamp}'
          crdate:
            value: '{__currentTimestamp}'
        elements:
          title:
            mapOnDatabaseColumn: title
          attachment:
            mapOnDatabaseColumn: fal_media
      -
        table: sys_file_reference
        mode: insert
        elements:
          attachment:
            mapOnDatabaseColumn: uid_local
        databaseColumnMappings:
          table_local:
            value: sys_file
          tablenames:
            value: tx_answers_domain_model_answer
          fieldname:
            value: fal_media
          tstamp:
            value: '{__currentTimestamp}'
          crdate:
            value: '{__currentTimestamp}'
          uid_foreign:
            value: '{SaveToDatabase.insertedUids.0}'
    identifier: SaveToDatabase
[...]
      -
        properties:
          saveToFileMount: '1:/user_upload/'
          allowedMimeTypes:
            - image/jpeg
            - image/png
            - image/bmp
          imageLinkMaxWidth: '500'
          imageMaxWidth: '500'
          imageMaxHeight: '500'
        type: ImageUpload
        identifier: attachment
        label: Attachment
```
...but this code allows to add only one file for upload

**How to add few files for upload and to save in the database?**
